### ISSUE TITLE
Assignment 3 checklist

### ISSUE THREAD

**Issue by sephlao** [sephlao/jarra#3]
**Application architecture**
- [x] Application must be structured  according to the MVC design pattern 
- [x] All sensitive credential information must be stored in an environment variable
- [x] Setup and configure MongoDB cloud service using MongoDB Atlas
- [x] Connect web app to mongoDB using an ODM service (Mongoose)
- [x] Name db and collections appropriately

**User registration module** 
- [x] Ensure that email from the registration form is unique (in my application I use the username as a unique value, no user should have the same username)
- [x] Password must not be stored in plain text in the db (bcryptjs)

**Authentication  module**
- [x] Application must allow an admin and regular user account
- [x] A session must be created and maintain the user state until they log out (use express.js session)
- [x] Application must be able to determine user type upon login and redirect to account-specific dashboard
- [x] Logout must destroy the session created by the authenticated user
- [x] Create specific routed that can only be accessed when users are logged-in

**Administrator module**
- [x] Admin must be able to perform CRUD functionality for rooms
- [x] Admin can set featured rooms and display such rooms in the hom page featured rooms section
- [x] Ensure that a user can only upload an image with the ff formats (jpg, gif, png)

**Search module**
- [x] Visitors should be able to search for rooms via location (add a search field in room listing page)
