### ISSUE TITLE
Assignment 4 checklist

### ISSUE THREAD

**Issue by sephlao** [sephlao/jarra#4]
**Room description page**
- [ ] Create a page that shows information about a specific room
- [ ] Add functionality that allows logged in users to book the room
- [ ] Room description page should have the following 
 - Room Image
 - Room title
 - Room description
 - Room price(per night)
 - Dates-Number of Nights (start date - end date)
 - Reserve Button
- [ ] When user clicks on `reserve` button, the room should be added to users booking cart

**Room Booking Module**
- [ ] User's dashboard should have a link to booking cart
- [ ] Booking cart page must display all rooms that were added by the user (nights for each room, total amount) *cost per room * number of nights = total cost
- [ ] Add place booking order button 
- [ ] When ^ button is clicked cart should be empty and an email must be sent to the user confirming the order and relevant information.
